# Generated by Django 3.2.6 on 2021-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.IntegerField()),
                ('dept', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
            ],
        ),
    ]
