# Generated by Django 3.2.6 on 2021-08-15 14:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1980), main.models.max_value_current_year])),
                ('rated', models.CharField(max_length=100)),
                ('released', models.DateField()),
                ('runtime', models.CharField(max_length=100)),
                ('genre', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('writer', models.TextField()),
                ('actors', models.TextField()),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('award', models.TextField()),
                ('poster', models.ImageField(upload_to='images/')),
                ('ratings', models.CharField(max_length=100)),
                ('metascore', models.CharField(max_length=50)),
                ('imdbRating', models.FloatField()),
                ('imdbVote', models.IntegerField()),
                ('imdbID', models.CharField(max_length=50)),
                ('Type', models.CharField(max_length=50)),
                ('dvd', models.DateField()),
                ('boxOoffice', models.CharField(max_length=100)),
                ('production', models.CharField(max_length=50)),
                ('response', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
            ],
        ),
    ]
