# Generated by Django 3.2.6 on 2021-08-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='award',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='boxOoffice',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='dvd',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbID',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbRating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdbVote',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='metascore',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='production',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
    ]
